#ifndef ADDPROCEVENT_H
#define ADDPROCEVENT_H

#include "baseevent.h"
#include "app.h"
#include <memory>
#include <iostream>

class AddProcEvent : public BaseEvent {

    std::shared_ptr<pc::App> app_;

public:

    AddProcEvent(std::shared_ptr<pc::App> app) : app_(app) {}

    void printOnOstream(std::ostream &os) const override {
        std::cout << "AddProcEvent generated by process " << app_->getPid() << std::endl;
    }

};

#endif // ADDPROCEVENT_H
