#ifndef ADDEVENT_H
#define ADDEVENT_H

#include "baseevent.h"
#include "../app.h"
#include <memory>
#include <iostream>

namespace rmcommon {

/*!
 * \class event generated by the WorkloadManager after validating
 * a ForkEvent or an AddRequestEvent.
 */
class AddEvent : public BaseEvent {

    std::shared_ptr<rmcommon::App> app_;

public:

    AddEvent(std::shared_ptr<rmcommon::App> app) :
        BaseEvent("AddEvent"),
        app_(app) {}

    std::shared_ptr<rmcommon::App> getApp() const {
        return app_;
    }

    void printOnOstream(std::ostream &os) const override {
        os << "{\"pid\":" << app_->getPid() << "}";
    }
};

}   // namespace rmcommon

#endif // ADDEVENT_H
