#ifndef ADDREQUESTEVENT_H
#define ADDREQUESTEVENT_H

#include "baseevent.h"
#include "../app.h"
#include <memory>
#include <iostream>

namespace rmcommon {

/*!
 * \class event generated by the Konro server when a request to add
 * a new process to Konro is received.
 */
class AddRequestEvent : public BaseEvent {

    std::shared_ptr<rmcommon::App> app_;

public:

    AddRequestEvent(std::shared_ptr<rmcommon::App> app) :
        BaseEvent("AddRequestEvent"),
        app_(app) {}

    std::shared_ptr<rmcommon::App> getApp() const {
        return app_;
    }

    void printOnOstream(std::ostream &os) const override {
        os << "{\"pid\":" << app_->getPid() << "}";
    }
};

}   // namespace rmcommon
#endif // ADDREQUESTEVENT_H
