#ifndef EXITEVENT_H
#define EXITEVENT_H

#include "baseevent.h"
#include <vector>
#include <cstdint>

namespace rmcommon {

/*!
 * \class exit event generated by the ProcListener
 */
class ExitEvent : public BaseEvent {
public:
    std::vector<std::uint8_t> data_;

    ExitEvent(const uint8_t *data, size_t len) :
        BaseEvent("ExitEvent"),
        data_(data, data+len)
    {
    }

    virtual void printOnOstream(std::ostream &os) const {
        os << "{}";
    }
};

}   // namespace rmcommon

#endif // EXITEVENT_H
