#ifndef FEEDBACKEVENT_H
#define FEEDBACKEVENT_H

#include "baseevent.h"
#include "../app.h"
#include <iomanip>
#include <sys/types.h>
#include <unistd.h>
#include <memory>

using namespace std;

namespace rmcommon {

/*!
 * \class event generated by the WorkloadManager after validating
 * a FeedbackRequestEvent.
 */
class FeedbackEvent : public BaseEvent {

    /*! The application sending the feedback */
    std::shared_ptr<rmcommon::App> app_;

    int feedback_;

public:
    FeedbackEvent(std::shared_ptr<rmcommon::App> app, int feedback) :
        BaseEvent("FeedbackEvent"),
        app_(app),
        feedback_(feedback)
    {}

    std::shared_ptr<rmcommon::App> getApp() const noexcept {
        return app_;
    }

    int getFeedback() const noexcept {
        return feedback_;
    }

    void printOnOstream(std::ostream &os) const override {
        ios_base::fmtflags f = os.flags();
        os.flags(f | ios_base::boolalpha);
        os << "{"
           << "\"pid\":" << app_->getPid()
           << ",\"feedback\":" << feedback_
           << "}";
        os.flags(f);
    }
};

} // namespace rmcommon

#endif // FEEDBACKEVENT_H
