#ifndef PROCFEEDBACKEVENT_H
#define PROCFEEDBACKEVENT_H

#include "baseevent.h"
#include <iomanip>

using namespace std;

namespace rmcommon {

/*!
 * \class event asynchronously generated by an integrated application.
 * This type of event is used by integrated applications to provide a
 * feedback to Konro regarding their QoS.
 */
class ProcFeedbackEvent : public BaseEvent {

    /* 0 = the current QoS level is sufficient
     * 1 = the current QoS level is insufficient
     */
    bool feedback_;

public:
    ProcFeedbackEvent(bool feedback) :
        feedback_(feedback)
    {}

    bool getFeedback() {
        return feedback_;
    }

    void printOnOstream(std::ostream &os) const override {
        ios_base::fmtflags f = os.flags();
        os.flags(f | ios_base::boolalpha);
        os << "{"
           << "\"feedback\":"
           << feedback_
           << "}";
        os.flags(f);
    }
};

} // namespace rmcommon

#endif // PROCFEEDBACKEVENT_H
