#ifndef PROCLISTENEREVENT_H
#define PROCLISTENEREVENT_H

#include "baseevent.h"
#include <string>
#include <vector>
#include <cstdint>

namespace rmcommon {

/*!
 * \class event generated by the ProcListener
 */
class ProcListenerEvent : public BaseEvent {
    std::vector<std::uint8_t> data_;
public:
    ProcListenerEvent(const uint8_t *data, size_t len) :
        BaseEvent("ProcListenerEvent"),
        data_(data, data+len)
    {
    }

    virtual void printOnOstream(std::ostream &os) const {
        os << "{}";
    }
};

}   // namespace rmcommon

#endif // PROCLISTENEREVENT_H
