#ifndef PROCLISTENERFORKEVENT_H
#define PROCLISTENERFORKEVENT_H

#include "baseevent.h"
#include <string>
#include <vector>
#include <cstdint>

namespace rmcommon {

/*!
 * \class fork event generated by the ProcListener
 */
class ProcListenerForkEvent : public BaseEvent {
public:
    std::vector<std::uint8_t> data_;

    ProcListenerForkEvent(const uint8_t *data, size_t len) :
        BaseEvent("ProcListenerForkEvent"),
        data_(data, data+len)
    {
    }

    virtual void printOnOstream(std::ostream &os) const {
        os << "{}";
    }
};

}   // namespace rmcommon

#endif // PROCLISTENERFORKEVENT_H
