#ifndef SECURITYEVENT_H
#define SECURITYEVENT_H

#include "baseevent.h"
#include "../app.h"
#include "../sai.h"
#include <memory>
#include <string>
#include <sys/types.h>
#include <unistd.h>

namespace rmcommon {

/*!
 * \class event generated by the SecurityMonitor when an anomaly
 * is detected in a managed application. Carries the composite
 * Security Anomaly Index (SAI, [0,1]), the per-factor breakdown,
 * and a CSV of human-readable threat labels.
 */
class SecurityEvent : public BaseEvent {

    std::shared_ptr<rmcommon::App> app_;
    float sai_;
    sec::SecurityFactors factors_;
    std::string labels_;

public:
    SecurityEvent(std::shared_ptr<rmcommon::App> app, float sai,
                  const sec::SecurityFactors &factors, const std::string &labels) :
        BaseEvent("SecurityEvent"),
        app_(app),
        sai_(sai),
        factors_(factors),
        labels_(labels)
    {}

    std::shared_ptr<rmcommon::App> getApp() const noexcept {
        return app_;
    }

    float getSai() const noexcept {
        return sai_;
    }

    const sec::SecurityFactors &getFactors() const noexcept {
        return factors_;
    }

    const std::string &getLabels() const noexcept {
        return labels_;
    }

    void printOnOstream(std::ostream &os) const override {
        os << "{"
           << "\"pid\":" << app_->getPid()
           << ",\"sai\":" << sai_
           << ",\"labels\":\"" << labels_ << "\""
           << "}";
    }
};

} // namespace rmcommon

#endif // SECURITYEVENT_H
